In [2]:
import numpy as np

In [12]:
def step(grid):
    rows, cols = grid.shape
    new_grid = np.zeros((rows, cols), dtype=np.int8)
    for i in range(rows):
        for j in range(cols):
            neighbors = get_neighbors(grid, i, j)
            count = sum(neighbors)
            if grid[i, j] == 1:
                if count in [2, 3]:
                    new_grid[i, j] = 1
            elif count == 3:
                new_grid[i, j] = 1
    return new_grid


def get_neighbors(grid, i, j):
    rows, cols = grid.shape
    indices = np.array([(i-1, j-1), (i-1, j), (i-1, j+1),
                        (i, j-1),             (i, j+1),
                        (i+1, j-1), (i+1, j), (i+1, j+1)])
    valid_indices = (indices[:, 0] >= 0) & (indices[:, 0] < rows) & \
                    (indices[:, 1] >= 0) & (indices[:, 1] < cols)
    #valid_indices[4] = False  # exclude current cell
    return grid[indices[valid_indices][:, 0], indices[valid_indices][:, 1]]


In [13]:
# Test
grid = np.array([[0, 0, 0, 0, 0],
                 [0, 0, 1, 0, 0],
                 [0, 1, 0, 1, 0],
                 [0, 0, 1, 0, 0],
                 [0, 0, 0, 0, 0]], dtype=np.int8)
step(grid)
print(grid)  # should be unchanged, but may change due to the bug

[[0 0 0 0 0]
 [0 0 1 0 0]
 [0 1 0 1 0]
 [0 0 1 0 0]
 [0 0 0 0 0]]


In [25]:
from functools import reduce
import re

def sum_of_squares(l):  
    # filter only to strings that can be cast to integers
    lnum = list(filter(lambda x: re.match("[-+]*[0-9]+", x), l))
    # square each number with map but cast the strings to int first
    lsq = list(map(lambda x: int(x)**2, lnum))
    # sum all the squared numbers
    return reduce(lambda a, b: a + b, lsq)

In [26]:
print(sum_of_squares(['1', '2', '3']))
print(sum_of_squares(['-1', '-2', '-3']))

14
14


In [27]:
print(sum_of_squares(['1', '2', '3']))
print(sum_of_squares(['-1', '-2', '-3']))
print(sum_of_squares(['1', '2', '#100', '3']))

14
14
14


In [45]:
import time

def time_this(func):
    """A decorator which times a function."""
    def inner(*args, **kwargs):
        t1 = time.process_time_ns()
        result = func(*args, **kwargs)
        t2 = time.process_time_ns()
        print("Processed in ", (t2 - t1)/1E9, " seconds")
        return result
    return inner

def measure_me(n):
    total = 0
    for i in range(n):
        total += i * i

    return total

# Redefine function
measure_me = time_this(measure_me)

In [46]:
print(measure_me(10000))
print(measure_me(100000))
print(measure_me(1000000))
print(measure_me(10000000))
print(measure_me(100000000))

Processed in  0.0  seconds
333283335000
Processed in  0.0  seconds
333328333350000
Processed in  0.0625  seconds
333332833333500000
Processed in  0.265625  seconds
333333283333335000000
Processed in  4.1875  seconds
333333328333333350000000


In [52]:
from multiprocessing import Pool

def filter_num(l):
    # filter only to strings that can be cast to integers
    return list(filter(lambda x: re.match("[-+]*[0-9]+", x), l))

def square_num(x):
    return int(x)**2

def sum_of_nums(l):  
    # sum all the numbers
    return reduce(lambda a, b: a + b, l)

In [54]:
# Generate a list of numbers to add up
test_nums = list(map(str, range(100+1)))

# Filter to valid numbers
valid_nums = filter_num(test_nums)

# Get the squares
if __name__ == '__main__':
    with Pool(5) as p:
        lsq = p.map(square_num, valid_nums)

print(sum_of_nums(lsq))