In [6]:
# Import libraries
import numpy
import time

In [4]:
# Read data
data = numpy.loadtxt(fname='../data/uniqplus_python_data/inflammation-01.csv', delimiter=',')
print(data)

[[0. 0. 1. ... 3. 0. 0.]
 [0. 1. 2. ... 1. 0. 1.]
 [0. 1. 1. ... 2. 1. 1.]
 ...
 [0. 1. 1. ... 1. 1. 1.]
 [0. 0. 0. ... 0. 2. 0.]
 [0. 0. 1. ... 1. 1. 0.]]


In [9]:
# Perform operations
print(numpy.mean(data))
print(time.ctime())

maxval, minval, stdval = numpy.max(data), numpy.min(data), numpy.std(data)

print('maximum inflammation:', maxval)
print('minimum inflammation:', minval)
print('standard deviation:', stdval)

6.14875
Thu May  9 15:39:16 2024
maximum inflammation: 20.0
minimum inflammation: 0.0
standard deviation: 4.613833197118566
